
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { AuditStatus, AuditReport } from "../types";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async runAudit(regulation: string, scenario: string, useSearch: boolean): Promise<AuditReport> {
    const prompt = `
      You are a high-precision Compliance Auditor. Your task is to perform a clinical analysis of a [Scenario] against a [Regulation].
      
      [Context]
      The regulation text might contain tabular data represented as CSV or text blocks. Pay close attention to row/column alignment.
      
      [Regulation]:
      ${regulation}
      
      [Scenario]:
      ${scenario}
      
      CRITICAL INSTRUCTIONS:
      1. ABSOLUTE ACCURACY: You must quote the relevant clauses from the regulation text EXACTLY as they appear. Do not paraphrase.
      2. LOGICAL RIGOR: Use step-by-step reasoning (Chain of Thought) to determine if the scenario violates any part of the regulation.
      3. STATUS: Determine if the result is "Violation", "Compliant", or "Uncertain".
      4. HIGHLIGHTING: In the "상세 분석" section, wrap the specific words or phrases that trigger a violation in <span class="highlight-red">text</span>.
      
      Output Format (Must follow strictly):
      ### ⚖️ 판정 결과: [위반 / 적합 / 판단 불가]
      ### 📜 관련 근거 조항
      > (규정 원문 조항 인용 - 오타 없이 정확하게)
      ### 🔍 상세 분석
      - (사안과 규정을 대조하여 위반/적합 여부를 논리적으로 설명)
      ### 💡 조치 권고 사항
      - (위반 시 해결책 또는 향후 방지책 제안)
    `;

    // Using gemini-3-pro-preview for complex reasoning and higher accuracy
    const response = await this.ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: prompt,
      config: {
        tools: useSearch ? [{ googleSearch: {} }] : undefined,
        thinkingConfig: { thinkingBudget: 4000 } // Reserve budget for complex reasoning
      },
    });

    const text = response.text || "No response generated.";
    
    let status = AuditStatus.UNCERTAIN;
    if (text.includes('위반') || text.toLowerCase().includes('violation')) status = AuditStatus.VIOLATION;
    else if (text.includes('적합') || text.toLowerCase().includes('compliant')) status = AuditStatus.COMPLIANT;

    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    const urls = groundingChunks?.map((chunk: any) => ({
      uri: chunk.web?.uri || chunk.maps?.uri,
      title: chunk.web?.title || chunk.maps?.title || "Reference"
    })).filter((u: any) => u.uri);

    return {
      status,
      rawMarkdown: text,
      groundingUrls: urls,
    };
  }

  async editImage(base64Image: string, prompt: string): Promise<string> {
    const cleanBase64 = base64Image.split(',')[1] || base64Image;
    
    const response = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/png',
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by Gemini");
  }
}
